post http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Front page of the web",
    "author": "i3c",
    "url": "example.com",
    "likes": "50",
    "userId": "5d6665c5cccd6867d8e17d72"
}